name: Build, Test and Deploy React Application

# Controls when the action will run.
on:
 # Triggers the workflow on push or pull request events but only for the main branch
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        node-version: [20.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          npm ci
          npm run jsdoc
          npm run build --if-present
          npm test 
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: build
          if-no-files-found: error
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Check if NPM package version has been updated
        run: |
         echo "Récupération de la version publiée sur npm..."
         PUBLISHED_VERSION=$(npm view ci-cd-ynov-julien-fertilati version || echo "0.0.0")
         echo "Version publiée : $PUBLISHED_VERSION"

         echo "Récupération de la version locale du package..."
         LOCAL_VERSION=$(node -p "require('./package.json').version")
         echo "Version locale : $LOCAL_VERSION"

         if [ "$PUBLISHED_VERSION" = "$LOCAL_VERSION" ]; then
            echo "La version locale est identique à celle publiée sur npm ($LOCAL_VERSION). Veuillez incrémenter la version dans package.json."
           exit 1
         else
           echo "La version locale est différente de celle sur npm. OK pour publier."
         fi
      - name: build and publish package on NPM
        run: |
          git config --global user.email "fertijulien@gmail.com"
          git config --global user.name "nefferou"
          npm run build-npm
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
  deploy:
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a page deployment
    permissions:
      pages: write
      id-token: write

    # Add a dependency to the build job
    needs: build_test
    # Specify runner + deployment step
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
         
